In [1]:
import numpy as np

In [2]:
# 生成ndarray
# np.array(list,dtype= np.float64 )
# dtype可通过a=a.astype(np.float64)转变
# shape可通过a=a.reshape(tuple)转型
tuple=(1,2,3)
np.empty(tuple)
# tuple为shape

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [3]:
# array的索引从0开始，且对切片的修改保存到对原数组上（都是视图）
# 拷贝，非视图，对数组的切片的复制，b=array [1:7，：，0] .copy()
# bool索引，array[true,false],因此array [x1 == X] #x1 in X#
# 取反~()
a=np.array([[1,2,3],[3,-1,2]])
a[a<0]
# 遍历每一个值

array([-1])

In [4]:
#神奇索引，和切片不同，复制到一个新的数组,arr2d[[1,-1]]第一行和最后一行
a=np.array([[1,2,3],[3,-1,2],[3,5,6]])
a[[1,0,2],[0,2,1]]
# 神奇索引选中的是（1，0），（0，2），（2，1）
# 和切片不同

array([3, 3, 5])

In [5]:
a[[1,0,2]][:,[0,2,1]]
# 切片

array([[ 3,  2, -1],
       [ 1,  3,  2],
       [ 3,  6,  5]])

In [6]:
# 转置a.T
a.T

array([[ 1,  3,  3],
       [ 2, -1,  5],
       [ 3,  2,  6]])

In [7]:
# 内积
np.dot(a.T,a)
#dot矩阵乘法

array([[19, 14, 27],
       [14, 30, 34],
       [27, 34, 49]])

In [8]:
# 置换轴arr.transpose((1,0,2)) 第二轴为第一轴，第一轴为第二轴，三轴不变

In [9]:
point=np.arange(1,5,1)
xs,ys=np.meshgrid(point,point)
# 生成网格
xs

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [10]:
np.where(xs==2,0,xs)
# 三元表达式的向量化版
# x if condition else y
# np.where(condition，x,y)
# 逐个元素判断

array([[1, 0, 3, 4],
       [1, 0, 3, 4],
       [1, 0, 3, 4],
       [1, 0, 3, 4]])

In [11]:
# 统计方法，如sum(axis=0)，std标准差，var方差

In [12]:
# bool数组，bool.any()是否有true,bool.all()是否全true

In [13]:
arr=np.random.randn(1,10)
arr

array([[-0.51968231,  1.41851922, -1.22738048, -1.00503638,  0.35964502,
         0.99000624, -0.78655168,  0.65500309,  0.89460073,  0.57738344]])

In [14]:
np.sort(arr)
# np.sort(arr)不修改arr
# arr.sort()修改arr

array([[-1.22738048, -1.00503638, -0.78655168, -0.51968231,  0.35964502,
         0.57738344,  0.65500309,  0.89460073,  0.99000624,  1.41851922]])

In [15]:
arr

array([[-0.51968231,  1.41851922, -1.22738048, -1.00503638,  0.35964502,
         0.99000624, -0.78655168,  0.65500309,  0.89460073,  0.57738344]])

In [16]:
# 一维ndarray，unique（arr）唯一值并排序,intersect1d(x,y)交并排序,union1d(x,y)并并排序

In [17]:
# np.save(),np.load()保存并读取，默认.npy
# np.savez('arr',a=arr2,b=arr3)保存多个数组，返回字典dict[a]=arr2

In [18]:
# np.dot(x,y)或x@y用于矩阵乘法，arr1*arr2用于逐个元素乘
arr2=np.random.randn(1,10)
arr2

array([[-0.66065828,  1.50178186, -0.4963439 , -0.18223624,  0.82917887,
         0.77959339, -1.33603669, -2.46148887,  0.51190541, -0.87595324]])

In [19]:
arr2*arr

array([[ 0.34333242,  2.13030643,  0.60920282,  0.18315405,  0.29821005,
         0.77180232,  1.05086191, -1.61228282,  0.45795095, -0.5057609 ]])

In [20]:
# np.linalg.矩阵包
# dot点乘，trace对角线和，det行列式，eig特征值特征向量，inv逆矩阵，qrQR分解，solve计算Ax=b的解，lstsq计算Ax=b最小二乘解

In [21]:
# np.random随机数包
# seed种子，rand均匀分布，randn标准正态分布，normal正太高斯分布，binomial二项分布，chisquare卡方分布，uniform01均匀分布